// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

// Injectors from wire.go:

func NewAppContainer() (*AppContainer, error) {
	appContainer := &AppContainer{}
	return appContainer, nil
}

// wire.go:

type AppContainer struct{}
